import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Thor',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Test1',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'PRO SERIES Jacket',
      slug: 'PRO-jacket',
      category: 'outerwear',
      image: '/images/jacket.jpg',
      price: 55,
      countInStock: 10,
      rating: 4.5,
      numReviews: 9,
      description: 'very nice jacket',
      isFeatured: true,
    },
    {
      name: 'PRO SERIES Hoodie',
      slug: 'PRO-hoodie',
      category: 'hoods',
      image: '/images/p2.jpg',
      price: 45,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: 'very cool hoodie. much nice',
      isFeatured: true,
    },
    {
      name: 'PRO SERIES Shirt',
      slug: 'pro-shirt',
      category: 'shirts',
      image: '/images/bmx3.jpg',
      price: 25,
      countInStock: 10,
      rating: 5,
      numReviews: 100,
      description: 'cool shirt, much wow, awesome!',
      isFeatured: true,
    },
    {
      name: 'PRO SERIES Short',
      slug: 'pro-short',
      category: 'pants',
      image: '/images/miata.jpg',
      price: 35,
      countInStock: 10,
      rating: 5,
      numReviews: 100,
      description: 'cool short, much wow, awesome!',
      isFeatured: true,
    },
    {
      name: 'PRO SERIES Skateboard',
      slug: 'pro-skate',
      category: 'accessories',
      image: '/images/skate.jpg',
      price: 65,
      countInStock: 5,
      rating: 5,
      numReviews: 25,
      description: 'High quality skateboard. Deck only.',
      isFeatured: false,
    },
    {
      name: 'PRO SERIES Hat',
      slug: 'pro-hat',
      category: 'accessories',
      image: '/images/hat.jpg',
      price: 22,
      countInStock: 15,
      rating: 4.5,
      numReviews: 50,
      description: 'High quality distressed dad hat.',
      isFeatured: false,
    },
    {
      name: 'PRO SERIES Pants',
      slug: 'pro-pant',
      category: 'pants',
      image: '/images/bmx.jpg',
      price: 25,
      countInStock: 15,
      rating: 5,
      numReviews: 50,
      description: 'High quality durable pants',
      isFeatured: false,
    },
    {
      name: 'PRO SERIES Button-Up T-Shirt',
      slug: 'pro-button-up',
      category: 'shirts',
      image: '/images/bmx2.jpg',
      price: 35,
      countInStock: 15,
      rating: 5,
      numReviews: 50,
      description: 'High quality button up t-shirt',
      isFeatured: false,
    },
    {
      name: 'PRO SERIES Poster',
      slug: 'pro-poster',
      category: 'misc',
      image: '/images/poster.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 4,
      description: 'High quality printed drift poster.',
      isFeatured: false,
    },
  ],
};

export default data;
